---

- id: lockeye
  name: "monitor code changes"
  language: python
  entry: lockeye
- id: exclude-marked
  name: "deny commit marked changes"
  language: python
  entry: exclude-marked
- id: sync-hash
  name: "validate generated files are in sync with sources"
  language: python
  entry: sync-hash
